import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from '@/utils/ReactQueryProvider';

export const metadata: Metadata = {
  title: 'Events.io',
  description: 'Generated by Reinmochi.Inc',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="modal"></div>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
