import type { Metadata } from 'next';
import '@splidejs/splide/dist/css/splide.min.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Events.io',
  description: 'Generated by Reinmochi.Inc',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
